### ISSUE TITLE
Wrong emotes show in chat and the menu

### ISSUE THREAD

**Issue by jraug44** [bttv-android/bttv#645] opened 2023-11-16 06:24 UTC
### Existing Issues

- [X] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [x] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

If you go to another channel's chat while watching a stream, that channel's emotes will show up in the chat of the stream you're watching and emote menu instead until you exit and reload the stream

### bttv-android version

v.0.40.4-beta

### android version

13

### device

Samsung S21 Ultra

**Comment by FoseFx** [comment] 2023-11-16 12:05
Duplicate of #264

**Closed by FoseFx** 2023-11-16 12:05 UTC
Labels: bug
