### ISSUE TITLE
"app non-installed" 

### ISSUE THREAD

**Issue by ARTH-V-R** [bttv-android/bttv#425] opened 2022-03-12 22:14 UTC
I'm using your app for 2 months, all was good until today when I tried to update, my download manager says "app non installed" at the end of the update download even if it worked perfectly before this update 😭

**Comment by FoseFx** [comment] 2022-03-12 22:24
"App not installed" could be caused by multiple reasons.

Do you have enough storage space left on the device?
What Android version are you on? Maybe the update is incompatible (even though the Twitch patch notes do not seem to mention this)

There are a couple of other things I have in mind but then everybody will have problems with updating and it seems to work just fine with both of my devices I use for testing.

Can you try to uninstall bttv-android and then install the new version by hand? https://github.com/bttv-android/bttv/releases/download/v0.23.0-beta/bttv-v0.23.0-beta.apk

**Comment by ARTH-V-R** [comment] 2022-03-12 22:34
> "App not installed" could be caused by multiple reasons.
> 
> Do you have enough storage space left on the device?
> What Android version are you on? Maybe the update broke compatibility (even though the Twitch patch notes do not seem to mention this)
> 
> There are a couple of other things I have in mind but then everybody will have problems with updating and it seems to work just fine with both of my devices I use for testing.
> 
> Can you try to uninstall bttv-android and then install the new version by hand? https://github.com/bttv-android/bttv/releases/download/v0.23.0-beta/bttv-v0.23.0-beta.apk
> 

I'm under android 10
I already tried to uninstall bttv-android and it didn't work...

**Comment by phroggster** [comment] 2022-03-13 02:31
I'm also on Android 10, plenty of free storage space, and am seeing this same issue. Uninstalled whatever prior version I had, then manually installed bttv-v0.23.0-beta.apk, and it fails with the same identical "App Not Installed" message that the updater was giving me.

**Comment by GuruAtomico** [comment] 2022-03-13 06:56
Wow!

I'm also experiencing this same problem. I've tried simple things like using the "force stopped" option in the app. Things like clearing storage or, reinstalling, I don't think it would do any good.

**Comment by linkmath** [comment] 2022-03-13 07:05
same thing happened to me so i uninstalled the twitch app and it worked. and now i can't reinstall the original twitch app from play store
maybe it's because of conflict provider name Between apps

**Comment by ARTH-V-R** [comment] 2022-03-13 08:08
> same thing happened to me so i uninstalled the twitch app and it worked. and now i can't reinstall the original twitch app from play store.
> maybe it's because of conflict provider name Between apps.

I did the same, I uninstalled twitch app and I worked

**Comment by FoseFx** [comment] 2022-03-13 08:16
@linkmath is right. In v12.5.2 Twitch added a new provider ("tv.twitch.android.app.androidx-startup"), which I missed in the update process. As the new version was not rolled out to me I could install it without a problem but now have issues updating the twitch app. For those who did update the Twitch App first it's the same but vice-versa.

Working on a fix

**Comment by FoseFx** [comment] 2022-03-13 08:28
@all-contributors please add @ARTH-V-R and @linkmath for bugs

**Comment by FoseFx** [comment] 2022-03-13 08:31
@all-contributors please add @linkmath for bugs

**Comment by FoseFx** [comment] 2022-03-13 08:35
Fixed by 0bbf0d6afc1d1114c1d2c0028fbf8137b8af365c please reopen if you still encounter this issue with v0.23.1-beta (which is deploying right now, takes about 10 minutes)

**Closed by FoseFx** 2022-03-13 08:35 UTC
Labels: bug, confirmed
