### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Koahollow** [bttv-android/bttv#697] opened 2024-12-09 20:18 UTC
### Existing Issues

- [ ] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [ ] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

You need to update the app...
The app said i need to update in playstore
Sorry for my English

**Comment by spfrgo** [comment] 2024-12-09 20:36
same for me

**Comment by Snowdac** [comment] 2024-12-09 23:25
A temporary solution until they can work around twitch is to delete everything related to this apk and reinstall. It's inconvenient but it does work

**Comment by FoseFx** [comment] 2024-12-10 09:20
Duplicate of #698 I guess? The title field is not optional.

**Closed by FoseFx** 2024-12-10 09:20 UTC
Labels: bug
