### ISSUE TITLE
7TV emotes not working after 7TV V2 API shutdown

### ISSUE THREAD

**Issue by jraug44** [bttv-android/bttv#634] opened 2023-11-02 18:43 UTC
### Existing Issues

- [x] I have searched for existing issues, this is not a duplicate.

### Unmodded Twitch

- [ ] I have checked and this issue only occurs using bttv-android and not with the unmodded Twitch App

### What happened?

7TV emotes are not showing up in chat right now and this is also an issue on desktop for lots of streamers who use certain chat overlays

### bttv-android version

v.0.40.1-beta

### android version

13

### device

Samsung S21 Ultra

### Anything else?

![Screenshot_20231102_133553_Discord](https://github.com/bttv-android/bttv/assets/149630943/a3742cc3-bf65-4d95-8645-582e0e1ede54)

**Comment by FoseFx** [comment] 2023-11-02 20:33
Duplicate of #633

**Closed by FoseFx** 2023-11-02 20:33 UTC
Labels: bug
