### ISSUE TITLE
Would Love To See /announce 

### ISSUE THREAD

**Issue by TheBaconSpace** [bttv-android/bttv#630] opened 2023-09-28 02:59 UTC
## Feature Request

**Is your feature request related to a problem? Please describe.**

Would Love To See /announce 

**Describe the solution you'd like**
Would Love To See /announce

**Comment by Zerwin** [comment] 2024-08-27 08:52
Might be a duplicate of #676 (I know that one came later but it is more comprehensive by now)

**Comment by FoseFx** [comment] 2024-08-27 09:25
Bug already opened on twitch: https://twitch.uservoice.com/forums/310222-twitch-applications-mobile/suggestions/45251569-allow-for-announcements-to-work-on-the-mobile-app

This is not a bttv issue, thus Twitch is responsible for fixing it.

Kind of crazy how long this thread is open though, thank you for raising it here too, though.

**Closed by FoseFx** 2024-08-27 09:25 UTC
Labels: feature request, base-bug
