### ISSUE TITLE
semi-auto delete when entering ttv emotes

### ISSUE THREAD

**Issue by freshkurt42** [bttv-android/bttv#482] opened 2022-06-24 00:05 UTC
hi I just noticed that when I do emotes and I try to delete them I have to hit the delete key manually not a big deal if you can implement the feature great if not oh well thanks again. 💙💯
also I submitted an issue a few days ago where the chat box wasn't coming up so I uninstalled the app and reinstalled the app and it fixed the problem thanks again.

**Comment by FoseFx** [comment] 2022-06-24 07:51
Duplicate of #334

**Closed by FoseFx** 2022-06-24 07:51 UTC
Labels: feature request
