### ISSUE TITLE
Chat stops updating randomly in vods

### ISSUE THREAD

**Issue by MrAl3x1s** [bttv-android/bttv#335] opened 2021-12-02 12:59 UTC
## Bug Report

**Current Behavior**
Chat messages in a vod stop coming in randomly and don't resume until the vod is closed and re-opened, even as the video continues normally, and chat messages were being sent at the time.

**Environment**

- bttv-android version: 0.16.0
- Android version: 11
- Device: samsung s10

**Comment by FoseFx** [comment] 2021-12-02 13:00
Duplicate of #327

**Closed by FoseFx** 2021-12-02 13:00 UTC
