### ISSUE TITLE
FEATURE REQUEST - CHAT ONLY MODE FIX

### ISSUE THREAD

**Issue by table9gaming** [bttv-android/bttv#494] opened 2022-07-07 23:00 UTC
When entering into "chat only mode" the top half of the screen is still taken up by empty space where the video was original playing. 

The only app I've seen do this right was mchat but that doesn't exist anymore of course and hasn't been updated in forever. 

Is there any way to fix this so that the chat will take up the whole screen? i know the app is based off of the official app so it may be something that's not possible,  just wanted to put this request up and see if this is even possible. 

thanks for a great app otherwise :)

**Comment by FoseFx** [comment] 2022-07-08 09:26
Duplicate of #490

**Closed by FoseFx** 2022-07-08 09:26 UTC
Labels: feature request
