### ISSUE TITLE
Background Audio won't close when I press the notifications buttons on android 6

### ISSUE THREAD

**Issue by shinelucid** [bttv-android/bttv#577] opened 2023-01-17 10:26 UTC
When I enable the play audio in background feature then switch apps, the notifications buttons appear but when I try to close the notification, it actually just stops the stream and doen't stop the app, and it sometimes persists and plays the stream automatically whenever audio focus is available and the notification buttons stay on even when I switch back to the app, the only way to stop the notification buttons is to force stop twitch, I wonder if it is mod related or a vanilla bug.

**Comment by FoseFx** [comment] 2023-01-17 10:37
sounds like a twitch bug, not caused by bttv-android. I'll close it as these kind of bugs are [out of scope](https://github.com/bttv-android/bttv/blob/master/CONTRIBUTING.md#not-in-scope) of the project. Feel free to re-open when you think this is a mistake.

**Closed by FoseFx** 2023-01-17 10:37 UTC
Labels: bug, unconfirmed, base bug likely
