### ISSUE TITLE
The chat freeze on vods

### ISSUE THREAD

**Issue by LEMIBANDDEXARI** [bttv-android/bttv#327] opened 2021-11-25 20:31 UTC
## Bug Report

**Current Behavior**
The chat freezes on the vods. We are two to have noticed this bug. This bug is new since the update v0.16.0-beta.

**Environment**

- bttv-android version: v0.16.0-beta

**Comment by FoseFx** [comment] 2021-11-27 13:08
I am watching a VOD for 15 minutes now and the chat replay still works fine. :/

Can you provide a link to a VOD and a timestamp which broke for you, so I can reproduce it?

**Comment by FoseFx** [comment] 2021-11-27 13:29
Update: I think the chat breaks when you click the three-dot button next to a chat message. Maybe this was the issue for you as well?

Update 2: I just confirmed the button issue with the unmodded twitch app, looks like a regression unrelated to bttv-android.

**Comment by LEMIBANDDEXARI** [comment] 2021-11-27 13:37
Here is who should help you understand
https://user-images.githubusercontent.com/70129787/143683604-84cdd9e2-1dcf-4148-833b-3260edd4bb49.mp4

and here is the original vod: https://www.twitch.tv/videos/1215923859
from streamer xQcOW

**Comment by LEMIBANDDEXARI** [comment] 2021-11-27 13:47
> Update: I think the chat breaks when you click the three-dot button next to a chat message. Maybe this was the issue for you as well?

No it's not because of that for us

**Comment by SekaiiArts** [comment] 2021-11-29 00:58
I can confirm this has been happening to me with this bttv app and the twitch app, latest versions of both on the latest version of android, it's been happening on any vod, subbed to streamer or not, and the only solution is to close the video and restart it, sometimes clearing ram and cache, however this is a temporary fix as, a few seconds to a couple minutes later the chat would pause once again. The chat for live content seems to be working as usual

**Comment by FoseFx** [comment] 2021-11-29 10:15
I could not reproduce it in bttv-android yet, but it did happen to me with the unmodded Twitch App, so I guess it's a Twitch bug. I opened a ticket and will keep y'all updated. As this is not a bttv-android bug, I will close this issue.

**Closed by FoseFx** 2021-11-29 10:15 UTC
Labels: bug

**Comment by FoseFx** [comment] 2021-12-08 19:14
> Hi fosefx,
Thank you for taking the time to give us additional information about the issue you are encountering.  We are currently looking into the situation and have raised this with the appropriate Developers for review.
 
We understand that this is frustrating and can be a major inconvenience. We deeply apologize for the nature of the issue. We appreciate you taking the time to report the issue.

**Comment by Itsfadixx** [comment] 2022-02-03 18:57
this also happens in twitchmod aswell

**Comment by shinelucid** [comment] 2022-02-06 13:57
An alternative solution is to open vod in chorme in desktop mode.
